### ISSUE TITLE
fix all GMXRC.* paths

### ISSUE THREAD

**Issue by orbeckst** [ianmkenney/conda-gromacs-5.1.2#2]
- [x] bash
- [x] csh
- [x] ~~ksh~~ (no GMXRC.ksh)
- [x] zsh

**Comment by orbeckst** [comment]
ALso don't use `?` as am alternatibe `sed` separator.

**Comment by ianmkenney** [comment]
Changed delimiters from `?` to `|` in 846c073f000994562d56e1ee8cbe2efb20275bb9

**Comment by ianmkenney** [comment]
efb6a5892c1269593c7d4553f62eb27bbe4fec3c
