### ISSUE TITLE
script to obtain path to GMXRC

### ISSUE THREAD

**Issue by orbeckst** [ianmkenney/conda-gromacs-5.1.2#3]
We need a way to get the path to `GMXRC`. Users (and GromacsWrapper) should be able to do something like

```
gmxrc=$(get_GMXRC 5.1.2)
source $gmxrc
```

**Comment by ianmkenney** [comment]
added in 17b33c4f0bb1e2bbc393719fe94fa30ea89d67be

installing via `conda install -c becksteinlab gromacs-5.1.2` adds the path to a hidden file in the home directory. The script is added to `$HOME` and to `~/.local/bin`. Has error handling and exit codes so it can be used easily in scripts.
